### ISSUE TITLE
conf is not defined

### ISSUE THREAD

**Issue by rajeshroy402** [HitPant/Jetson_Project_1#1]
Hi, I am using Jetson Xavier NX as the host machine. I made changes to the config.json file for the video source and replaced it with the file:///home/$USER/Downloads/video.mp4 without double quotes and saved the file. Here is the error I'm getting.

> Configuration file missing!
> [INFO] setting preferable backend and target to CUDA...
> Traceback (most recent call last):
>   File "loiter_dwell_detection.py", line 240, in <module>
>     main_thread = main()
>   File "loiter_dwell_detection.py", line 130, in main
>     cap = cv2.VideoCapture(conf["vid_source"])
> NameError: name 'conf' is not defined

**Comment by HitPant** [comment]
Hi Rajesh,

the following is defined at the top of the program:
**conf = json.load(open("./config.json")) #loads the values from config file**
1. make sure this is not commented.
2. make sure "vid_source" is defined on the config file as well.
